host: 'localhost'
port: '3306'
db: 'seichiassist'
id: 'root'
pw: 'uzFpcJxYcPYArqBT'
defaultmineamount: '3'
minutespeedamount: '0.01'
onlineplayersamount: '0.2'
presentinterval: '1000'
activeminelevel: '10'
dropexplevel: '8'
passiveportalinventorylevel: '16'
lv1message: '/spawnと打つとスポーン地点に戻ることができます.有効に活用してください.    整地鯖では死んでもロストしません.気軽に冒険,整地してくださいね.'
lv2message: 'ブランチマイニングは資源サーバーでお願いします.                           資源サーバーへ行くには、/spawnと入力してください.'
lv3message: '左手に何か持ち（F）、右手が素手の状態でスニークしながら右クリックすると,  採掘速度上昇を無効化できます'
lv4message: '個人のチェストは盗まれないように保護をかけてください.                     /cprivate と入力し、保護したいチェストを叩くことで保護できます.'
lv5message: '自分の家を守るためにも、家全体に保護をかけてください.保護方法については   公式wiki(http://seichi.click/)に詳しい説明があります.'
lv6message: 'Dynmapでどこに誰がいるのか,何があるのかなどを見ることができます.↓URL     http://mc.seichi.click:8123'
lv7message: 'あと300ブロックほど破壊するとガチャ券を獲得できます！                     ガチャ券を右クリックすると豪華景品が獲得できるかも？'
lv8message: 'おめでとうございます！新しいパッシブスキル[追加経験値獲得]を解除しました！特定のブロック破壊で確率で追加経験値を獲得できるようになりました！'
lv9message: '採掘速度上昇の内訳を知りたいですか？/ef smartと打つと内訳を見れます！'
lv10message: 'おめでとうございます！経験値を消費して2段破壊ができるようになりました！  ダイヤピッケル、ダイヤシャベル、ダイヤ斧のいずれかを持った状態で      スニークしながら右クリックすると発動できます！'
lv11message: '整地鯖をもっと良くするために,是非JPMCSに投票をお願いします.↓URL         https://minecraft.jp/servers/seichi.click/vote'
lv12message: '何か不具合を見つけたら、管理者まで報告してください.'
lv13message: ''
lv14message: ''
lv15message: ''
lv16message: 'おめでとうございます！新しいパッシブスキル[4次元ポケット]を解除しました！/ef dr と打つと4次元ポケットを受け取ることができます！'
lv17message: 'このレベル以降はレベル自体は上昇しますが、スキルは未実装です。           ひたすら整地に精進しましょう。何かいいことがあるかもしれませんよ。'
lv18message: ''
lv19message: ''
lv20message: ''
lv21message: ''
lv22message: ''
lv23message: ''
lv24message: ''
lv25message: ''
lv26message: ''
lv27message: ''
lv28message: ''
lv29message: ''
lv30message: ''
lv31message: ''
lv32message: ''
lv33message: ''
lv34message: ''
lv35message: ''
lv36message: ''
lv37message: ''
lv38message: ''
lv39message: ''
lv40message: ''
lv41message: ''
lv42message: ''
lv43message: ''
lv44message: ''
lv45message: ''
lv46message: ''
lv47message: ''
lv48message: ''
lv49message: ''
lv50message: ''
lv51message: ''
lv52message: ''
lv53message: ''
lv54message: ''
lv55message: ''
lv56message: ''
lv57message: ''
lv58message: ''
lv59message: ''
lv60message: ''
lv61message: ''
lv62message: ''
lv63message: ''
lv64message: ''
lv65message: ''
lv66message: ''
lv67message: ''
lv68message: ''
lv69message: ''
