name: SeichiAssist
main: com.github.unchama.seichiassist.SeichiAssist
version: 0.2.6

commands:
  gacha:
      description: This is a gacha command.
      usage: /<command> <add/list/remove/clear>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  seichi:
      description: This is a seichi command.
      usage: /<command> <playername/bug/test> <duration(tick)/get/set> <amplifier(double)>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  ef:
      description: This is a Effect toggle command.
      usage: /<command> <smart>
      permission: multiseichiplugin.ef
      permission-message: You don't have <permission>
  level:
      description: This is a level command.
      usage: /<command> <reset>
      permission: multiseichiplugin.level
      permission-message: You don't have <permission>